#!/usr/bin/env bash
# Write a bash script that display information about the subdomains

#domain_info () {
#	script=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
#	echo "$2 $script" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
#}

#if [ "$#" == 1 ]
#then
#  domain_info "$1" "www"
#  domain_info "$1" "lb-01"
#  domain_info "$1" "web-01"
#  domain_info "$1" "web-02"
#elif [ "$#" == 2 ]
#then
#  domain_info "$1" "$2"
#fi

subdomains_all=( "www" "lb-01" "web-01" "web-02" )

runDig () {
    subdomain=$1
    domain=$2

    dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -1 | awk -v s="$subdomain" 'BEGIN { FS = " " } ; { print "The subdomain " s " is a " $4 " record and points to " $5 }'
}

if [ $# -eq 1 ]; then
    domain="$1"
    for i in "${subdomains_all[@]}"
    do
	runDig "$i" "$domain"
    done
elif [ $# -eq 2 ]; then
    domain="$1"
    subdomain="$2"
    runDig "$subdomain" "$domain"
fi
