#!/bin/bash
cat -n | grep [13579][[:space:]] | tr -s ' ' | cut -f2cat -n | grep [13579][[:space:]] | tr -s ' ' | cut -f2cat -n | grep [13579][[:space:]] | tr -s ' ' | cut -f2cat -n | grep [13579][[:space:]] | tr -s ' ' | cut -f:wq

