#!/usr/bin/env bash
#this script echos "Best School" ten times on the console
n=10
while [ $n -gt 0 ]
do
	if [ $n -gt 1 ]
	then
		echo "Best School"
	else
		echo "Hi"
		echo "Best School"
	fi
	((n--))
done
