#!/usr/bin/env bash
#Displays "bad luck", "good luck" and "Best school" in some iterations
k=0
while [ $k -lt 10 ]
do
	if [ $k -eq 3 ]
	then
		echo "bad luck"
	elif [ $k -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((k++))
done
